### searchCompany
GET http://localhost:8080/company/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMDU4ODU0LCJleHAiOjE3MDIwNjI0NTR9.SiP6HOJRzsgqlaZs30nPnPyvNdyDSC-I8aimZQePcVFyaOYGEdpYLosf-4A-C5LjrNCyQ9Zn20wKOZo_3EOgHA



### addCompany
POST http://localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMDU5MTAwLCJleHAiOjE3MDIwNjI3MDB9.z1KV3vIB6tmLlSqZxDPjbbsgvSWs9hNaWqA5h5MOsI8UrFmtK2RysKeTzoqbV0I6BF992Jg6rsGzOjagIpnPbw

{
  "ticker": "MMM"
}

### autocomplete
GET http://localhost:8080/company/autocomplete?keyword=I
Accept: application/json

### deleteCompany
DELETE http://localhost:8080/company/MMM
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMDU4ODU0LCJleHAiOjE3MDIwNjI0NTR9.SiP6HOJRzsgqlaZs30nPnPyvNdyDSC-I8aimZQePcVFyaOYGEdpYLosf-4A-C5LjrNCyQ9Zn20wKOZo_3EOgHA


