### searchCompany
GET http://localhost:8080/company
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMTkxNjM0LCJleHAiOjE3MDIxOTUyMzR9.TQApAS3MQphud8l8xuZCyAEFpH8RMfVL2MtGTQNtFLMdArwFixqxvxWvU9VjRcxEqiWghjLrSQ0CXTkA2Uv85g


### addCompany
POST http://localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMTkxNjM0LCJleHAiOjE3MDIxOTUyMzR9.TQApAS3MQphud8l8xuZCyAEFpH8RMfVL2MtGTQNtFLMdArwFixqxvxWvU9VjRcxEqiWghjLrSQ0CXTkA2Uv85g

{
  "ticker": "NIKE"
}

### autocomplete
GET http://localhost:8080/company/autocomplete?keyword=I
Accept: application/json

### deleteCompany
DELETE http://localhost:8080/company/MMM
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzAyMTkxNjM0LCJleHAiOjE3MDIxOTUyMzR9.TQApAS3MQphud8l8xuZCyAEFpH8RMfVL2MtGTQNtFLMdArwFixqxvxWvU9VjRcxEqiWghjLrSQ0CXTkA2Uv85g



